services:
  app:
    build: .
    develop:
      watch:
      - action: sync
        path: ./src
        target: /app/src/
        initial_sync: true
    ports:
      - "${COMPOSE_SERVER_PORT:-3001}:3001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${COMPOSE_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
