"""Add building address index

Revision ID: c1fd91ef14eb
Revises: 37b5686bfef0
Create Date: 2026-01-18 04:18:28.109440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1fd91ef14eb'
down_revision: Union[str, Sequence[str], None] = '37b5686bfef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_building_address', 'buildings', ['address'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_building_address', table_name='buildings', postgresql_using='gin')
    # ### end Alembic commands ###
